server:
    port: 8080
# spring config
spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    config:
        use-legacy-processing: true
    profiles:
        # add import modules profile
        include:
            - data
            - api-repository
            - member-api
            - image-store
            - s3
            - batch
walking:
    batch:
        schedular:
            interval: ${SCHEDULER_INTERVAL}
    predict:
        dataInterval: ${DATA_INTERVAL}
        maximumSearchCount: ${MAXIMUM_SEARCH_COUNT}

# security config
security:
    jwt:
        token:
            validtime:
                access: ${ACCESS_TOKEN_VALIDTIME}
                refresh: ${REFRESH_TOKEN_VALIDTIME}
            secretkey: ${TOKEN_SECRETKEY}
    cors:
        path-patterns: ${CORS_PATH_PATTERNS}
        origin-patterns: ${CORS_ORIGIN_PATTERNS}
        allowed-methods: ${CORS_ALLOWED_METHODS}
        allowed-headers: ${CORS_ALLOWED_HEADERS}
        exposed-headers: ${CORS_EXPOSED_HEADERS}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS}
        max-age: ${CORS_MAX_AGE}
