server:
    port: 8080

# spring config
spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    config:
        use-legacy-processing: true
    profiles:
        # add import modules profile
        include:
            - data-local
            - api-repository-local
            - member-api-local
            - image-store-local
            - minio
            - batch-local

walking:
    batch:
        schedular:
            interval: 70
    predict:
        dataInterval: 20
        maximumSearchCount: 5

# security config
security:
    jwt:
        token:
            validtime:
                access: 31557600000
                refresh: 31557600000
            secretkey: jwtsecretKeyhastolonghowlongidontknow
    cors:
        path-patterns: "/**"
        origin-patterns: "http://localhost:3000"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Set-Cookie, Authorization, Content-Type, X-Requested-With, Accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Allow-Origin, Access-Control-Allow-Credentials"
        allow-credentials: true
        max-age: 1800

# api docs config
springdoc:
    swagger-ui:
        url: /docs/openapi3.yaml
        path: /swagger

logging:
    level:
        com.walking: DEBUG
        org.springframework.cache: TRACE
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
