client:
  max-attempts: 3
  pool:
    max-connect: 100
    max-connect-per-route: 5
  timeout:
    connect: 5000
    read: 5000
  retry:
      maxAttempts: 3
      backOffPeriod: 2000

kakao:
  host: https://kauth.kakao.com
  adminKey: adminKey
  uri:
    token: https://kauth.kakao.com/oauth/token
    token_info: https://kapi.kakao.com/v1/user/access_token_info
    me_info: https://kapi.kakao.com/v2/user/me
    unlink: https://kapi.kakao.com/v1/user/unlink
  redirect_uri: http://localhost:8080/api/v1/social/kakao
  client_id: thisIsKaKaoClientId
