api:
    datasource:
        jdbc-url: jdbc:mysql://localhost:13306/api?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 50
