server:
  port: 18888
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - client-local
      - mysql-local
      - batch-local
        
        log-local

# batch config
walking:
  batch:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:13306/batch?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jdbc:
      initialize-schema: always
    job:
      enabled: ${job.name:NONE}

# log config
log:
  file:
    path: ./var/log/walking/batch