spring:
    batch:
        datasource:
            jdbcUrl: ${DB_HOSTNAME}/batch?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
            username: ${DB_USERNAME}
            password: ${DB_PASSWORD}
            driver-class-name: com.mysql.cj.jdbc.Driver
            maximum-pool-size: 5
            minimum-idle: 3
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
        chunk:
            size: 1000
        jdbc:
            initialize-schema: always
        job:
            enabled: false
            names: ${job.name:NONE}

api:
    traffic:
        seoul:
            apiKey: ${SEOUL_API_KEY}
            baseUrl: http://t-data.seoul.go.kr
            colorPath: /apig/apiman-gateway/tapi/v2xSignalPhaseInformation/1.0
            timeLeftPath: /apig/apiman-gateway/tapi/v2xSignalPhaseTimingInformation/1.0
